name: Automatic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Extract the latest version from CHANGELOG.md
        id: changelog
        run: |
          latest_version=$(grep -oP "^## \K[0-9]+\.[0-9]+\.[0-9]+" CHANGELOG.md | head -n 1)
          echo "Latest version: $latest_version"
          echo "::set-output name=version::$latest_version"

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          latest_version=$(grep -oP "^## \K[0-9]+\.[0-9]+\.[0-9]+" CHANGELOG.md | head -n 1)
          git tag -a "v$latest_version" -m "Release $latest_version"
          git push origin "v$latest_version"

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.changelog.outputs.version }}"
          release_name: "v${{ steps.changelog.outputs.version }}"
          body: |
            $(awk '/^## / {f=0} f; /^## \K[0-9]+\.[0-9]+\.[0-9]+/{f=1}' CHANGELOG.md)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
