describe("TCPListener", function()
  it("can be start", function()
    local listener = require("assistant.core.tcplistener").new()
    assert.is_nil(listener.server)
    listener:start()
    assert.not_nil(listener.server)
    listener:stop()
    assert.is_true(listener.server:is_closing())
  end)
end)
