name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest changelog
        id: changelog
        run: |
          LATEST_CHANGELOG=$(awk '/^## [0-9]+\.[0-9]+\.[0-9]+/ { if (found) exit; found=1 } found' CHANGELOG.md)
          echo "LATEST_CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$LATEST_CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.LATEST_CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
